import type { NextApiRequest, NextApiResponse } from "next";
import { db } from "@/lib/db";
import {
  Document as DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  BorderStyle,
  convertInchesToTwip,
  Footer,
  PageNumber,
  NumberFormat,
} from "docx";

// ── HTML → plain paragraphs ───────────────────────────────────────────────────
// Drafts are stored as HTML (generated by workspace.ts). Strip tags to get
// plain text paragraphs suitable for Word / PDF rendering.

function htmlToLines(html: string): string[] {
  const text = html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<\/h[1-6]>/gi, "\n")
    .replace(/<\/li>/gi, "\n")
    .replace(/<li[^>]*>/gi, "• ")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\r\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return text.split("\n").map((l) => l.trimEnd());
}

function safeFilename(title: string, date: string, ext: string): string {
  const slug = title.replace(/[^a-zA-Z0-9\-_ ]/g, "").replace(/\s+/g, "-").slice(0, 60);
  const d = date.replace(/\//g, "-");
  return `${slug}-${d}.${ext}`;
}

// ── Word export ───────────────────────────────────────────────────────────────

async function buildDocx(
  lines: string[],
  draftTitle: string,
  docName: string,
  dateStr: string,
  disclaimer: string
): Promise<Buffer> {
  const NAVY = "1B2A5E";
  const GRAY = "767676";
  const LIGHT_GRAY = "A8A8A8";

  // Header rows
  const headerParagraphs = [
    new Paragraph({
      children: [
        new TextRun({
          text: "LEXX DOCUMENT INTELLIGENCE",
          bold: true,
          size: 28, // 14pt
          font: "Arial",
          color: NAVY,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `${draftTitle}  ·  ${docName}  ·  ${dateStr}`, size: 18, font: "Arial", color: GRAY }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
    }),
    // Horizontal rule via paragraph border
    new Paragraph({
      border: { bottom: { color: "D4D4D4", style: BorderStyle.SINGLE, size: 6 } },
      spacing: { after: 240 },
    }),
  ];

  // Body paragraphs (skip blank lines that would create excessive whitespace)
  const bodyParagraphs = lines.map(
    (line) =>
      new Paragraph({
        children: [new TextRun({ text: line, size: 22, font: "Arial" })],
        spacing: { after: line.trim() === "" ? 60 : 140 },
      })
  );

  // Disclaimer footer block inside the body
  const footerBlock = [
    new Paragraph({ spacing: { before: 480 } }),
    new Paragraph({
      border: { top: { color: "E8E8E8", style: BorderStyle.SINGLE, size: 4 } },
      spacing: { before: 0, after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: disclaimer, italics: true, size: 16, font: "Arial", color: LIGHT_GRAY }),
      ],
    }),
  ];

  const docx = new DocxDocument({
    sections: [
      {
        properties: {
          page: {
            size: {
              width: 12240, // US Letter width in twips
              height: 15840, // US Letter height in twips
            },
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
            },
          },
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ children: ["Page ", PageNumber.CURRENT, " of ", PageNumber.TOTAL_PAGES], size: 16, font: "Arial", color: LIGHT_GRAY }),
                ],
                alignment: AlignmentType.CENTER,
                numbering: undefined,
              }),
            ],
          }),
        },
        children: [...headerParagraphs, ...bodyParagraphs, ...footerBlock],
      },
    ],
    numbering: {
      config: [{ reference: "page-num", levels: [{ level: 0, format: NumberFormat.DECIMAL, text: "%1", alignment: AlignmentType.CENTER }] }],
    },
  });

  return Packer.toBuffer(docx);
}

// ── PDF export ────────────────────────────────────────────────────────────────

async function buildPdf(
  lines: string[],
  draftTitle: string,
  docName: string,
  dateStr: string,
  disclaimer: string
): Promise<Buffer> {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const PDFDocument = require("pdfkit") as typeof import("pdfkit");

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 72, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const NAVY = "#1B2A5E";
    const GRAY = "#767676";
    const LIGHT = "#A8A8A8";

    // ── Header ──
    doc.font("Helvetica-Bold").fontSize(14).fillColor(NAVY).text("LEXX DOCUMENT INTELLIGENCE", { align: "center" });
    doc.moveDown(0.4);
    doc.font("Helvetica").fontSize(9).fillColor(GRAY).text(`${draftTitle}  ·  ${docName}  ·  ${dateStr}`, { align: "center" });
    doc.moveDown(0.8);
    doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor("#D4D4D4").lineWidth(0.5).stroke();
    doc.moveDown(0.8);

    // ── Body ──
    doc.font("Helvetica").fontSize(11).fillColor("#0A0A0A");

    for (const line of lines) {
      if (line.trim() === "") {
        doc.moveDown(0.5);
      } else {
        doc.text(line, { align: "left" });
        doc.moveDown(0.3);
      }
    }

    // ── Disclaimer ──
    doc.moveDown(1.5);
    doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).strokeColor("#E8E8E8").lineWidth(0.5).stroke();
    doc.moveDown(0.5);
    doc.font("Helvetica-Oblique").fontSize(8).fillColor(LIGHT).text(disclaimer, { align: "left" });

    // ── Page numbers ──
    const totalPages = doc.bufferedPageRange().count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      const oldBottomMargin = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc
        .font("Helvetica")
        .fontSize(8)
        .fillColor(LIGHT)
        .text(`Page ${i + 1} of ${totalPages}`, 72, doc.page.height - 40, { align: "center" });
      doc.page.margins.bottom = oldBottomMargin;
    }

    doc.end();
  });
}

// ── Handler ───────────────────────────────────────────────────────────────────

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") return res.status(405).end();

  const { id } = req.query;
  if (typeof id !== "string") return res.status(400).json({ error: "Invalid id" });

  const format = ((req.query.format as string) || "docx").toLowerCase();
  if (format !== "docx" && format !== "pdf") {
    return res.status(400).json({ error: "Unsupported format. Use docx or pdf." });
  }

  const draft = await db.getDraft(id);
  if (!draft) return res.status(404).json({ error: "Draft not found" });

  const doc = draft.documentId ? await db.getDocument(draft.documentId) : null;
  const docName = (doc?.fileName ?? "Document").replace(/\.[^.]+$/, ""); // strip extension
  const dateStr = new Date(draft.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const lines = htmlToLines(draft.content);

  try {
    if (format === "docx") {
      const buffer = await buildDocx(lines, draft.title, docName, dateStr, draft.disclaimer);
      const filename = safeFilename(draft.title, dateStr, "docx");
      res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
      res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
      return res.send(buffer);
    }

    if (format === "pdf") {
      const buffer = await buildPdf(lines, draft.title, docName, dateStr, draft.disclaimer);
      const filename = safeFilename(draft.title, dateStr, "pdf");
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
      return res.send(buffer);
    }
  } catch (err) {
    console.error("[Lexx:export] Export failed:", err);
    return res.status(500).json({ error: "Export failed. Please try again." });
  }
}
